apiVersion: batch/v1
kind: Job
metadata:
  name: patrickstestcontainer
spec:
  template:
    spec:
      containers:
      - name: patrickstestcontainer
        image: patricksblog.azurecr.io/repo:patrickstestcontainer
      nodeSelector: 
        kubernetes.io/os: linux
      restartPolicy: Never
  backoffLimit: 4